### ISSUE TITLE
Addon Exits immediately with error 132

### ISSUE THREAD

**Issue by kidhasmoxy** [asmirnou/watsor-hassio-addons#2]
No logs recorded, just an instant error status of 132. Running on a miniPC running the homeassistant NUC image. No Coral and an Intel J5005 processor, which does have dri available. 

Running it after the initial crash records the following error in the logs. 

```
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 382 leaked semaphores to clean up at shutdown
  len(cache))
```

**Comment by asmirnou** [comment]
Can it be caused by [this one](https://github.com/tensorflow/tensorflow/issues/19584)?

As a workaround the Coral may help as Tensorflow libraries are not loaded then.

Building Watsor from source along with the dependencies may work as well, but it is tough way.

**Comment by kidhasmoxy** [comment]
Yes, it is an AVX issue. I installed a Coral, but now have an issue where the addon reports the following. The Coral is there, but python isn't able to run the model. 
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/watsor/detection/detector.py", line 86, in _run
    with detector_class(*detector_args) as object_detector:
  File "/usr/local/lib/python3.6/dist-packages/watsor/detection/edge_tpu.py", line 15, in __init__
    device_path=device_path)
  File "/usr/lib/python3/dist-packages/edgetpu/detection/engine.py", line 71, in __init__
    super().__init__(model_path, device_path)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 90, in __init__
    model_path, device_path)
RuntimeError: Error in device opening (/sys/bus/usb/devices/2-5)!
```

**Comment by asmirnou** [comment]
Could you install the add-on from another [branch](https://github.com/asmirnou/watsor-hassio-addons/tree/full_access) (change Add-on Store), where full access is enabled? After installing the add-on disable protection mode to activate full access. 

That error has been seen in Raspberry Pi images, where USB accelerator wasn't detected properly without the privileged mode. The add-on as such doesn't require full access, but I wonder whether it may help you too.

**Comment by kidhasmoxy** [comment]
I had tried forking the addon and rebuilding it with tweaks and rebooting, powering with different PSU, nothing worked. Ultimately the fix came with the latest OS upgrade for homeassistant (4.13). Everything works as expected after upgrading. Closing the issue, thank you so much for your help.

**Comment by kidhasmoxy** [comment]
Quick update, I was using my custom addon, which works as of the 4.13 os update. These are the items in my config.json that help with issues starting the addon: 

  "usb": "true",
  "video": "true",
  "devicetree": "true",
