### ISSUE TITLE
How to install on Docker Home Assistant?

### ISSUE THREAD

**Issue by strarsis** [asmirnou/watsor-hassio-addons#4]
Docker Home Assistant seems to be different as Docker container, as there is no "supervisor" with which I can install addons from GitHub repositories.
Can I use HACS instead? I searched for `watsor`, but nothing is found, I also tried using this repository URL (https://github.com/asmirnou/watsor-hassio-addons) directly.

Would Watsor be similar to Frigate? Can I use it to get notified when e.g. the postman is at the door (even get a screen grab so I can see whether it is a false positive)?

**Comment by asmirnou** [comment]
Yes, it is similar, but this repository is for Hassio addons and they are [different](https://hacs.xyz/docs/faq/addons) from HACS integration. There is no Watsor integration for HACS at the moment.

**Comment by strarsis** [comment]
@asmirnou: Can I install it on a Docker container or is Hassio strictly required for this?

**Comment by asmirnou** [comment]
It will not be an easy way. I'll need to repeat [these steps](https://github.com/asmirnou/watsor/blob/master/docker/Dockerfile.base) in docker container to install the dependencies.

**Comment by strarsis** [comment]
@asmirnou: Though this is offtopic and more of a question: Can I use hassio with docker? Or is it something that is meant to run natively?

**Comment by asmirnou** [comment]
I think you can as there is Docker [container](https://www.home-assistant.io/installation/linux#install-home-assistant-container) for Hassio. It will not support addons inside the container, but you can install Watsor's Docker [container](https://github.com/asmirnou/watsor#docker) in your OS and connect them together via MQTT [container](https://hub.docker.com/_/eclipse-mosquitto).
